Vagrant.configure("2") do |config|

  config.vm.box = "bandit145/centos_stream9_arm"

  config.vm.network "private_network", ip: "192.168.56.88"
  config.vm.network "public_network"

  config.vm.provider "vmware_desktop" do |vb|
    vb.gui = true
    vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
    yum install httpd wget unzip git -y
    systemctl start httpd
    systemctl enable httpd
    mkdir /opt/devopsdir
    free -m
    uptime
    systemctl stop firewalld
    systemctl disable firewalld
  SHELL

end