Vagrant.configure("2") do |config|

    config.vm.box = "spox/ubuntu-arm" 
    config.vm.box_version = "1.0.0"
  
    # Prive network with static IP
    config.vm.network "private_network", ip: "192.168.56.19"  
    # Public network (bridged), no static IP
    config.vm.network "public_network"

    # Synced folder: host folder to guest folder
    config.vm.synced_folder "./scripts", "/opt/scripts"

    config.vm.provider "vmware_desktop" do |vb|
        vb.ssh_info_public = true
        vb.gui = true
        vb.memory = "1600"
        vb.cpus = "2"
    end

end