Vagrant.configure("2") do |config|

   config.vm.box = "bandit145/centos_stream9_arm"
   config.vm.network "private_network", ip: "192.168.56.28"

   config.vm.provider "vmware_desktop" do |vb|
      vb.gui = true
      vb.memory = "1024"
   end

   config.vm.provision "shell", inline: <<-SHELL
      yum install httpd wget unzip vim -y
      systemctl start httpd
      systemctl enabled httpd
      mkdir -p /tmp/finance
      cd /tmp/finance
      wget https://www.tooplate.com/zip-templates/2135_mini_finance.zip
      unzip -o 2135_mini_finance.zip
      cp -r 2135_mini_finance/* /var/www/html/
      systemctl restart httpd
      cd /tmp/
      rm -rf /tmp/finance
      systemctl stop firewalld
      systemctl disable firewalld
   SHELL

end