Vagrant.configure("2") do |config|

  config.vm.box = "bandit145/centos_stream9_arm"
  
  config.vm.network "private_network", ip: "192.168.56.22"
  
  config.vm.provider "vmware_desktop" do |vb|
    vb.gui = true
    vb.memory = "1024"
  end

end